$ErrorActionPreference='Stop'; Set-StrictMode -Version Latest
$Root=Split-Path -Parent $PSScriptRoot
$ServerProject=Join-Path $Root 'server-dotnet\AVASurface.Server.csproj'; $ServerDir=Join-Path $Root 'server-dotnet'; $Dist=Join-Path $Root 'dist'; $WebRoot=Join-Path $ServerDir 'wwwroot'; $Artifacts=Join-Path $Root 'artifacts'; $Publish=Join-Path $Artifacts 'publish'; $Bundle=Join-Path $Artifacts 'efbundle.exe'; $Iss=Join-Path $Root 'deployment\installer\VeroBillingExistingSql.iss'; $Out=Join-Path $Root 'deployment\output'
function Need($n){if(-not(Get-Command $n -EA SilentlyContinue)){throw "Required command '$n' was not found."}}
Need node;Need npm;Need dotnet
if(-not(Test-Path $Iss)){throw "Installer script not found: $Iss"}
$Inno=Join-Path $env:ProgramFiles 'Inno Setup 7\ISCC.exe'; if(-not(Test-Path $Inno)){$Inno=Join-Path ${env:ProgramFiles(x86)} 'Inno Setup 7\ISCC.exe'}; if(-not(Test-Path $Inno)){throw 'Inno Setup 7 ISCC.exe was not found.'}
Write-Host '1/6 Frontend dependencies/build' -ForegroundColor Yellow; Push-Location $Root; try{npm ci;if($LASTEXITCODE){throw 'npm ci failed'};npm run lint;if($LASTEXITCODE){throw 'npm run lint failed'};npm run build;if($LASTEXITCODE){throw 'npm run build failed'}}finally{Pop-Location}
if(-not(Test-Path (Join-Path $Dist 'index.html'))){throw 'Frontend build did not produce dist/index.html.'}
Write-Host '2/6 Combining frontend' -ForegroundColor Yellow;if(Test-Path $WebRoot){Remove-Item $WebRoot -Recurse -Force};New-Item -ItemType Directory $WebRoot -Force|Out-Null;Copy-Item (Join-Path $Dist '*') $WebRoot -Recurse -Force
Write-Host '3/6 Publishing backend' -ForegroundColor Yellow;if(Test-Path $Artifacts){Remove-Item $Artifacts -Recurse -Force};New-Item -ItemType Directory $Publish -Force|Out-Null;Push-Location $ServerDir;try{dotnet restore $ServerProject -r win-x64;if($LASTEXITCODE){throw 'dotnet restore failed'};dotnet build $ServerProject -c Release --no-restore;if($LASTEXITCODE){throw 'dotnet build failed'};dotnet publish $ServerProject -c Release -r win-x64 --self-contained true --no-restore -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -p:DebugType=None -o $Publish;if($LASTEXITCODE){throw 'dotnet publish failed'}}finally{Pop-Location}
Write-Host '4/6 Creating EF bundle' -ForegroundColor Yellow;$env:ASPNETCORE_ENVIRONMENT='Production';$ef=(& dotnet ef --version 2>$null|Select-Object -Last 1);if($ef -notmatch '9\.0\.8'){throw "dotnet-ef 9.0.8 required; found $ef"};Push-Location $ServerDir;try{dotnet ef migrations bundle --project $ServerProject --startup-project $ServerProject --self-contained --target-runtime win-x64 --output $Bundle --force;if($LASTEXITCODE){throw 'EF migration bundle failed'}}finally{Pop-Location}
Write-Host '5/6 Compiling installer' -ForegroundColor Yellow;if(Test-Path $Out){Remove-Item $Out -Recurse -Force};New-Item -ItemType Directory $Out -Force|Out-Null;& $Inno $Iss;if($LASTEXITCODE){throw 'Inno Setup compilation failed'}
$Setup=Get-ChildItem $Out -Filter '*.exe'|Sort-Object LastWriteTime -Descending|Select-Object -First 1;if(-not$Setup){throw 'Installer EXE was not produced'};Write-Host '=== BUILD COMPLETE ===' -ForegroundColor Green;Write-Host $Setup.FullName -ForegroundColor Green
