// <auto-generated />
using System;
using AVASurface.Server.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AVASurface.Server.Migrations;

[DbContext(typeof(BillingDbContext))]
[Migration("20260817103000_AddAppUserPasswordHash")]
partial class AddAppUserPasswordHash
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        modelBuilder.HasAnnotation("ProductVersion", "9.0.8");
        modelBuilder.Entity("AVASurface.Server.Domain.AppUser", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
            b.Property<string>("UserName").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
            b.Property<string>("DisplayName").IsRequired().HasMaxLength(150).HasColumnType("nvarchar(150)");
            b.Property<string>("Role").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.Property<bool>("IsActive").HasColumnType("bit");
            b.Property<string>("PasswordHash").HasMaxLength(500).HasColumnType("nvarchar(500)");
            b.Property<DateTime>("CreatedAtUtc").HasColumnType("datetime2");
            b.HasKey("Id");
            b.HasIndex("UserName").IsUnique();
            b.ToTable("AppUsers");
        });
    }
}
