import React from 'react';
import { Invoice, BusinessStoreDetails } from '../types';
import { formatCurrency, formatDateTime } from '../lib/utils';
import { Printer, X } from 'lucide-react';

interface PrintableReceiptModalProps { invoice: Invoice | null; onClose: () => void; storeDetails: BusinessStoreDetails; }
const money = (value: number | undefined, symbol: string) => formatCurrency(value ?? 0, symbol);

const amountInWords = (value: number): string => {
  const ones = ['', 'One', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine', 'Ten', 'Eleven', 'Twelve', 'Thirteen', 'Fourteen', 'Fifteen', 'Sixteen', 'Seventeen', 'Eighteen', 'Nineteen'];
  const tens = ['', '', 'Twenty', 'Thirty', 'Forty', 'Fifty', 'Sixty', 'Seventy', 'Eighty', 'Ninety'];
  const two = (n: number) => n < 20 ? ones[n] : `${tens[Math.floor(n / 10)]}${n % 10 ? ` ${ones[n % 10]}` : ''}`;
  const under = (n: number) => { const p: string[] = []; if (Math.floor(n / 100)) p.push(`${ones[Math.floor(n / 100)]} Hundred`); if (n % 100) p.push(two(n % 100)); return p.join(' '); };
  const whole = Math.floor(Math.abs(value)); const paise = Math.round((Math.abs(value) - whole) * 100); let n = whole; const p: string[] = [];
  const crore = Math.floor(n / 10000000); n %= 10000000; const lakh = Math.floor(n / 100000); n %= 100000; const thousand = Math.floor(n / 1000); n %= 1000;
  if (crore) p.push(`${under(crore)} Crore`); if (lakh) p.push(`${under(lakh)} Lakh`); if (thousand) p.push(`${under(thousand)} Thousand`); if (n) p.push(under(n));
  return `${value < 0 ? 'Minus ' : ''}${p.join(' ') || 'Zero'} Rupees${paise ? ` and ${two(paise)} Paise` : ''} Only`;
};

export const PrintableReceiptModal: React.FC<PrintableReceiptModalProps> = ({ invoice, onClose, storeDetails }) => {
  if (!invoice) return null;
  const customer = invoice.customer;
  const totalDiscount = Number(invoice.itemDiscountsTotal || 0) + Number(invoice.promoDiscountAmount || 0) + Number(invoice.branchManagerDiscountAmount || 0);
  const managerApproved = Number(invoice.branchManagerDiscountAmount || 0) > 0 || !!invoice.branchManagerUserId;
  const taxable = Number(invoice.subtotal || 0) - totalDiscount;
  const pages: Invoice['items'][] = [];
  for (let i = 0; i < invoice.items.length; i += 12) pages.push(invoice.items.slice(i, i + 12));
  if (!pages.length) pages.push([]);

  return <div className="fixed inset-0 z-50 bg-slate-950/80 flex items-center justify-center p-4 overflow-y-auto print:static print:bg-white print:p-0">
    <style>{`@page{size:A4;margin:8mm}@media print{body{background:white!important}body>*{visibility:hidden}.ava-print-root,.ava-print-root *{visibility:visible}.ava-print-root{position:absolute;inset:0;width:100%;background:white}.ava-invoice-page{width:100%;min-height:281mm;page-break-after:always;box-shadow:none!important}.ava-invoice-page:last-child{page-break-after:auto}.print-hide{display:none!important}`}</style>
    <div className="ava-print-root w-full max-w-5xl max-h-[calc(100vh-2rem)] overflow-y-auto">
      <div className="p-3 bg-slate-900 text-white flex items-center justify-between print-hide rounded-t-lg sticky top-0 z-10"><span className="font-bold text-sm">AVA Surfaces — Tax Invoice Preview</span><div className="flex gap-2"><button onClick={() => window.print()} className="px-4 py-2 bg-white text-slate-900 rounded font-bold text-sm flex items-center gap-2"><Printer className="w-4 h-4"/>Print / PDF</button><button onClick={onClose} className="p-2 bg-slate-800 rounded"><X className="w-4 h-4"/></button></div></div>
      <div className="bg-white text-black shadow-2xl">
        {pages.map((pageItems, pageIndex) => { const last = pageIndex === pages.length - 1; return <section key={pageIndex} className="ava-invoice-page p-5 text-[10px] leading-tight">
          <header className="border border-black">
            <div className="grid grid-cols-[115px_1fr_170px] min-h-[90px]"><div className="border-r border-black flex items-center justify-center"><div className="text-center"><div className="text-[42px] leading-none font-black tracking-[-6px] text-[#b51f2a]">AVA</div><div className="text-[12px] tracking-[5px] font-bold">SURFACES</div></div></div><div className="p-3 text-center"><div className="text-[18px] font-black uppercase">AVA SURFACES PVT LIMITED</div><div className="font-semibold mt-1">{storeDetails.address}</div><div className="mt-1">Phone: {storeDetails.phone}{storeDetails.email ? ` | Email: ${storeDetails.email}` : ''}</div><div className="font-bold mt-1">GSTIN: {storeDetails.taxRegistrationNumber}{storeDetails.pan ? ` | PAN: ${storeDetails.pan}` : ''}</div></div><div className="border-l border-black p-2"><div className="font-black text-center border-b border-black pb-1">TAX INVOICE</div><div className="grid grid-cols-2 gap-1 mt-2"><b>Invoice No.</b><span>{invoice.invoiceNumber}</span><b>Date</b><span>{formatDateTime(invoice.date)}</span>{invoice.ewayBillNo&&<><b>E-Way Bill</b><span>{invoice.ewayBillNo}</span></>}</div></div></div>
            <div className="grid grid-cols-2 border-t border-black"><div className="p-2 border-r border-black min-h-[78px]"><div className="font-black uppercase border-b border-black pb-1 mb-1">Buyer Details</div><div className="font-bold">{customer?.name || 'Customer Required'}</div><div>{customer?.address || 'Address required'}</div>{customer?.phone&&<div>Mobile: {customer.phone}</div>}{customer?.gstNumber&&<div className="font-bold">GSTIN: {customer.gstNumber}</div>}</div><div className="p-2 min-h-[78px]"><div className="font-black uppercase border-b border-black pb-1 mb-1">Sales & Delivery</div><div>Salesperson: <b>{invoice.salespersonName || invoice.cashierName || '-'}</b></div><div>Mobile: {invoice.salespersonMobile || '-'}</div><div>Vehicle: {invoice.vehicleNumber || '-'}</div>{invoice.transporterName&&<div>Transporter: {invoice.transporterName}</div>}{invoice.trackingNumber&&<div>Tracking: {invoice.trackingNumber}</div>}</div></div>
          </header>
          <table className="w-full mt-2 border-collapse border border-black table-fixed"><thead><tr className="font-black text-center"><th className="border border-black p-1 w-[28px]">S.No</th><th className="border border-black p-1 w-[35%]">Description of Goods</th><th className="border border-black p-1 w-[65px]">HSN/SAC</th><th className="border border-black p-1 w-[45px]">GST %</th><th className="border border-black p-1 w-[45px]">Qty</th><th className="border border-black p-1 w-[55px]">Unit</th><th className="border border-black p-1 w-[75px]">Actual Rate</th><th className="border border-black p-1 w-[55px]">Disc %</th><th className="border border-black p-1">Amount</th></tr></thead><tbody>{pageItems.map((item,index)=><tr key={`${pageIndex}-${index}`}><td className="border border-black p-1 text-center">{pageIndex*12+index+1}</td><td className="border border-black p-1 font-semibold">{item.product.name}</td><td className="border border-black p-1 text-center">{item.product.hsnCode||'-'}</td><td className="border border-black p-1 text-center">{item.product.taxRate}%</td><td className="border border-black p-1 text-right">{item.inputQuantity ?? item.quantity}</td><td className="border border-black p-1 text-center">{item.selectedUnit || item.product.unit || '-'}</td><td className="border border-black p-1 text-right">{money(item.product.sellingPrice,storeDetails.currencySymbol)}</td><td className="border border-black p-1 text-right">{item.discountPercent??0}%</td><td className="border border-black p-1 text-right">{money(item.totalPrice,storeDetails.currencySymbol)}</td></tr>)}{Array.from({length:Math.max(0,12-pageItems.length)}).map((_,i)=><tr key={`blank-${pageIndex}-${i}`} className="h-[21px]"><td colSpan={9} className="border-x border-black">&nbsp;</td></tr>)}</tbody></table>
          {!last&&<div className="font-bold italic mt-2 text-right">Continued........</div>}
          {last&&<>
            <div className="grid grid-cols-[1fr_260px] gap-2 mt-2"><div className="border border-black p-2"><div className="font-black uppercase mb-1">Billing Summary</div><div className="grid grid-cols-2 gap-y-1"><span>Actual Amount</span><b>{money(invoice.subtotal,storeDetails.currencySymbol)}</b><span>Total Discount</span><b>-{money(totalDiscount,storeDetails.currencySymbol)}</b>{managerApproved&&<><span className="font-bold">Approval</span><b>MANAGER APPROVED</b></>}{invoice.branchManagerRemarks&&<><span>Approval Note</span><b>{invoice.branchManagerRemarks}</b></>}</div></div><div className="border border-black p-2 space-y-1"><div className="flex justify-between"><span>Actual Amount</span><b>{money(invoice.subtotal,storeDetails.currencySymbol)}</b></div><div className="flex justify-between"><span>Total Discount</span><b>-{money(totalDiscount,storeDetails.currencySymbol)}</b></div><div className="flex justify-between"><span>Taxable Value</span><b>{money(taxable,storeDetails.currencySymbol)}</b></div>{invoice.cgstAmount!==undefined&&<div className="flex justify-between"><span>CGST</span><b>{money(invoice.cgstAmount,storeDetails.currencySymbol)}</b></div>}{invoice.sgstAmount!==undefined&&<div className="flex justify-between"><span>SGST</span><b>{money(invoice.sgstAmount,storeDetails.currencySymbol)}</b></div>}{invoice.igstAmount!==undefined&&invoice.igstAmount>0&&<div className="flex justify-between"><span>IGST</span><b>{money(invoice.igstAmount,storeDetails.currencySymbol)}</b></div>}<div className="flex justify-between"><span>Round Off</span><b>{money(invoice.roundOffAmount,storeDetails.currencySymbol)}</b></div><div className="flex justify-between border-t border-black pt-1 text-sm"><b>Grand Total</b><b>{money(invoice.grandTotal,storeDetails.currencySymbol)}</b></div></div></div>
            {(invoice.warehouseLoadedBy || invoice.warehouseVerifiedBy || invoice.warehouseLoadedAtUtc || invoice.warehouseRemarks || invoice.deliveredByName) && <div className="border border-black mt-2 p-2"><div className="font-black uppercase border-b border-black pb-1 mb-1">Warehouse / Dispatch Completion</div><div className="grid grid-cols-2 gap-x-4 gap-y-1"><span>Loaded By</span><b>{invoice.warehouseLoadedBy || '-'}</b><span>Verified By</span><b>{invoice.warehouseVerifiedBy || '-'}</b><span>Vehicle</span><b>{invoice.vehicleNumber || '-'}</b><span>Completed At</span><b>{invoice.warehouseLoadedAtUtc ? formatDateTime(invoice.warehouseLoadedAtUtc) : '-'}</b>{invoice.deliveredByName&&<><span>Delivered / Verified By</span><b>{invoice.deliveredByName}</b></>}{invoice.deliveredAtUtc&&<><span>Delivery Completed</span><b>{formatDateTime(invoice.deliveredAtUtc)}</b></>}{invoice.warehouseRemarks&&<><span>Warehouse Remarks</span><b>{invoice.warehouseRemarks}</b></>}</div></div>}
            <div className="grid grid-cols-2 gap-2 mt-2"><div className="border border-black p-2 min-h-[55px]"><b>Total Amount in Words:</b><br/>{amountInWords(invoice.grandTotal)}</div><div className="border border-black p-2 min-h-[55px]"><b>Tax Amount in Words:</b><br/>{amountInWords(invoice.taxTotal)}</div></div>
            <div className="border border-black mt-2 p-2"><b>Declaration:</b> Goods once sold are subject to the terms and conditions of sale. E. &amp; O. E.</div>
            <div className="flex justify-between items-end mt-8 px-2"><div className="font-semibold">Customer Signature</div><div className="text-right font-bold">For AVA SURFACES PVT LIMITED<br/><br/>Authorised Signatory</div></div>
          </>}
        </section>; })}
      </div>
    </div>
  </div>;
};