using AVASurface.Server.Domain;
using Microsoft.EntityFrameworkCore;
namespace AVASurface.Server.Infrastructure;
public sealed class BillingDbContext(DbContextOptions<BillingDbContext> options) : DbContext(options)
{
 public DbSet<Company> Companies=>Set<Company>(); public DbSet<Customer> Customers=>Set<Customer>(); public DbSet<Salesperson> Salespersons=>Set<Salesperson>(); public DbSet<Product> Products=>Set<Product>(); public DbSet<Promotion> Promotions=>Set<Promotion>(); public DbSet<AppUser> AppUsers=>Set<AppUser>(); public DbSet<Invoice> Invoices=>Set<Invoice>(); public DbSet<InvoiceLine> InvoiceLines=>Set<InvoiceLine>(); public DbSet<Payment> Payments=>Set<Payment>(); public DbSet<StockTransaction> StockTransactions=>Set<StockTransaction>(); public DbSet<AuditLog> AuditLogs=>Set<AuditLog>();
 protected override void OnModelCreating(ModelBuilder modelBuilder)
 {
  modelBuilder.Entity<Company>(e=>{e.HasKey(x=>x.Id);e.Property(x=>x.Code).HasMaxLength(30).IsRequired();e.Property(x=>x.LegalName).HasMaxLength(200).IsRequired();e.Property(x=>x.Gstin).HasMaxLength(15);e.HasIndex(x=>x.Code).IsUnique();});
  modelBuilder.Entity<Customer>(e=>{e.HasKey(x=>x.Id);e.Property(x=>x.Code).HasMaxLength(50).IsRequired();e.Property(x=>x.Name).HasMaxLength(200).IsRequired();e.Property(x=>x.Phone).HasMaxLength(30);e.Property(x=>x.Gstin).HasMaxLength(15);e.Property(x=>x.City).HasMaxLength(100);e.Property(x=>x.State).HasMaxLength(100);e.Property(x=>x.StateCode).HasMaxLength(10);e.Property(x=>x.Pincode).HasMaxLength(20);e.Property(x=>x.CustomerType).HasMaxLength(20).IsRequired();e.HasIndex(x=>new{x.CompanyId,x.Code}).IsUnique();e.HasOne(x=>x.Company).WithMany(x=>x.Customers).HasForeignKey(x=>x.CompanyId).OnDelete(DeleteBehavior.Restrict);});
  modelBuilder.Entity<Salesperson>(e=>{e.HasKey(x=>x.Id);e.Property(x=>x.Code).HasMaxLength(30).IsRequired();e.Property(x=>x.Name).HasMaxLength(150).IsRequired();e.Property(x=>x.Mobile).HasMaxLength(15).IsRequired();e.HasIndex(x=>new{x.CompanyId,x.Code}).IsUnique();e.HasOne(x=>x.Company).WithMany(x=>x.Salespersons).HasForeignKey(x=>x.CompanyId).OnDelete(DeleteBehavior.Restrict);});
  modelBuilder.Entity<Product>(e=>{e.HasKey(x=>x.Id);e.Property(x=>x.Sku).HasMaxLength(80).IsRequired();e.Property(x=>x.Name).HasMaxLength(250).IsRequired();e.Property(x=>x.Barcode).HasMaxLength(100);e.Property(x=>x.Category).HasMaxLength(120);e.Property(x=>x.HsnCode).HasMaxLength(8);e.Property(x=>x.Unit).HasMaxLength(20).IsRequired();e.Property(x=>x.CostPrice).HasPrecision(18,2);e.Property(x=>x.SellingPrice).HasPrecision(18,2);e.Property(x=>x.GstRate).HasPrecision(5,2);e.Property(x=>x.StockQuantity).HasPrecision(18,3);e.Property(x=>x.ReorderLevel).HasPrecision(18,3);e.Property(x=>x.PcsPerBox).HasPrecision(18,3);e.Property(x=>x.SqftPerBox).HasPrecision(18,3);e.Property(x=>x.PricePerSqFt).HasPrecision(18,3);e.Property(x=>x.WeightPerBoxKg).HasPrecision(18,3);e.HasIndex(x=>new{x.CompanyId,x.Sku}).IsUnique();e.HasOne(x=>x.Company).WithMany(x=>x.Products).HasForeignKey(x=>x.CompanyId).OnDelete(DeleteBehavior.Restrict);});
  modelBuilder.Entity<Promotion>(e=>{e.HasKey(x=>x.Id);e.Property(x=>x.Code).HasMaxLength(50).IsRequired();e.Property(x=>x.Name).HasMaxLength(150).IsRequired();e.Property(x=>x.DiscountPercent).HasPrecision(5,2);e.Property(x=>x.MaxDiscountPercent).HasPrecision(5,2);e.Property(x=>x.ProductCategory).HasMaxLength(120);e.Property(x=>x.CustomerType).HasMaxLength(20);e.HasIndex(x=>new{x.CompanyId,x.Code}).IsUnique();e.HasOne(x=>x.Company).WithMany(x=>x.Promotions).HasForeignKey(x=>x.CompanyId).OnDelete(DeleteBehavior.Restrict);});
  modelBuilder.Entity<AppUser>(e=>{e.HasKey(x=>x.Id);e.Property(x=>x.UserName).HasMaxLength(100).IsRequired();e.Property(x=>x.DisplayName).HasMaxLength(150).IsRequired();e.Property(x=>x.Role).HasMaxLength(30).IsRequired();e.HasIndex(x=>x.UserName).IsUnique();e.HasOne(x=>x.Company).WithMany().HasForeignKey(x=>x.CompanyId).OnDelete(DeleteBehavior.Restrict);});
  modelBuilder.Entity<Invoice>(e=>{e.HasKey(x=>x.Id);e.Property(x=>x.QuotationNumber).HasMaxLength(50).IsRequired();e.Property(x=>x.InvoiceNumber).HasMaxLength(50).IsRequired(false);e.Property(x=>x.SalespersonName).HasMaxLength(150).IsRequired();e.Property(x=>x.SalespersonMobile).HasMaxLength(15).IsRequired();e.Property(x=>x.SubTotal).HasPrecision(18,2);e.Property(x=>x.DiscountAmount).HasPrecision(18,2);e.Property(x=>x.PromoDiscountPercent).HasPrecision(5,2);e.Property(x=>x.PromoDiscountAmount).HasPrecision(18,2);e.Property(x=>x.BranchManagerDiscountPercent).HasPrecision(5,2);e.Property(x=>x.BranchManagerDiscountAmount).HasPrecision(18,2);e.Property(x=>x.CreditNoteAmount).HasPrecision(18,2);e.Property(x=>x.BranchManagerRemarks).HasMaxLength(500);e.Property(x=>x.CreditNoteReason).HasMaxLength(500);e.Property(x=>x.WorkflowStatus).HasMaxLength(40).IsRequired();e.Property(x=>x.PaymentConfirmedByName).HasMaxLength(150);e.Property(x=>x.PaymentMethodConfirmed).HasMaxLength(30);e.Property(x=>x.PaymentSpecificReference).HasMaxLength(200);e.Property(x=>x.PaymentBankName).HasMaxLength(150);e.Property(x=>x.PaymentCardLast4).HasMaxLength(4);e.Property(x=>x.PaymentUtr).HasMaxLength(100);e.Property(x=>x.PaymentRemarks).HasMaxLength(500);e.Property(x=>x.WarehouseLoadedBy).HasMaxLength(150);e.Property(x=>x.WarehouseVerifiedBy).HasMaxLength(150);e.Property(x=>x.WarehouseVehicleNumber).HasMaxLength(30);e.Property(x=>x.WarehouseRemarks).HasMaxLength(500);e.Property(x=>x.DeliveredByName).HasMaxLength(150);e.Property(x=>x.DeliveryRemarks).HasMaxLength(500);e.Property(x=>x.TaxableAmount).HasPrecision(18,2);e.Property(x=>x.CgstAmount).HasPrecision(18,2);e.Property(x=>x.SgstAmount).HasPrecision(18,2);e.Property(x=>x.IgstAmount).HasPrecision(18,2);e.Property(x=>x.RoundOffAmount).HasPrecision(18,2);e.Property(x=>x.GrandTotal).HasPrecision(18,2);e.HasIndex(x=>new{x.CompanyId,x.InvoiceNumber}).IsUnique();e.HasIndex(x=>new{x.CompanyId,x.QuotationNumber}).IsUnique();e.HasIndex(x=>new{x.CompanyId,x.WorkflowStatus,x.InvoiceDate});e.HasOne(x=>x.Company).WithMany(x=>x.Invoices).HasForeignKey(x=>x.CompanyId).OnDelete(DeleteBehavior.Restrict);e.HasOne(x=>x.Customer).WithMany().HasForeignKey(x=>x.CustomerId).OnDelete(DeleteBehavior.Restrict);e.HasOne(x=>x.Salesperson).WithMany(x=>x.Invoices).HasForeignKey(x=>x.SalespersonId).OnDelete(DeleteBehavior.Restrict);});
  modelBuilder.Entity<InvoiceLine>(e=>{e.HasKey(x=>x.Id);e.Property(x=>x.Quantity).HasPrecision(18,3);e.Property(x=>x.UnitPrice).HasPrecision(18,2);e.Property(x=>x.DiscountPercent).HasPrecision(5,2);e.Property(x=>x.DiscountAmount).HasPrecision(18,2);e.Property(x=>x.TaxableAmount).HasPrecision(18,2);e.Property(x=>x.CgstAmount).HasPrecision(18,2);e.Property(x=>x.SgstAmount).HasPrecision(18,2);e.Property(x=>x.IgstAmount).HasPrecision(18,2);e.Property(x=>x.LineTotal).HasPrecision(18,2);e.HasOne(x=>x.Invoice).WithMany(x=>x.Lines).HasForeignKey(x=>x.InvoiceId).OnDelete(DeleteBehavior.Cascade);e.HasOne(x=>x.Product).WithMany().HasForeignKey(x=>x.ProductId).OnDelete(DeleteBehavior.Restrict);});
  modelBuilder.Entity<Payment>(e=>{e.HasKey(x=>x.Id);e.Property(x=>x.Amount).HasPrecision(18,2);e.Property(x=>x.Method).HasMaxLength(30).IsRequired();e.HasOne(x=>x.Invoice).WithMany(x=>x.Payments).HasForeignKey(x=>x.InvoiceId).OnDelete(DeleteBehavior.Cascade);});
  modelBuilder.Entity<StockTransaction>(e=>{e.HasKey(x=>x.Id);e.Property(x=>x.QuantityChange).HasPrecision(18,3);e.Property(x=>x.TransactionType).HasMaxLength(40).IsRequired();e.HasOne(x=>x.Product).WithMany().HasForeignKey(x=>x.ProductId).OnDelete(DeleteBehavior.Restrict);});
  modelBuilder.Entity<AuditLog>(e=>{e.HasKey(x=>x.Id);e.Property(x=>x.Action).HasMaxLength(100).IsRequired();e.Property(x=>x.EntityName).HasMaxLength(100).IsRequired();});
 }
}
