from pathlib import Path

path = Path("src/components/ModernPosBillingView.tsx")
text = path.read_text(encoding="utf-8")
old = "const created=onAddNewCustomer({name:newCustomer.name.trim(),phone:newCustomer.phone.trim(),address:newCustomer.address.trim(),billingAddress:newCustomer.address.trim(),shippingAddress:newCustomer.address.trim(),city:newCustomer.city.trim(),state:newCustomer.state.trim(),stateCode:newCustomer.stateCode.trim(),gstNumber:newCustomer.gstNumber.trim()||undefined,customerType,email:undefined,loyaltyPoints:0,totalSpent:0,outstandingBalance:0} as any);try{const response=await fetch(`/api/billing-categories/customer/${created.id}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({categoryId:billingCategoryId})});if(!response.ok)throw new Error('Unable to map customer to the selected billing category.');setCustomer(created);setCategoryCustomers(cur=>[created,...cur.filter(c=>c.id!==created.id)]);setCreatingCustomer(false);setShowCustomerPanel(false);setNewCustomer(emptyCustomer);setMessage('Customer created and mapped to the selected billing category.')}catch(e){setMessage(e instanceof Error?e.message:'Customer created, but category mapping failed. Please ask a manager to map the customer.')}"
new = "try{const companiesResponse=await fetch('/api/companies');if(!companiesResponse.ok)throw new Error(`Company API HTTP ${companiesResponse.status}`);const companies=await companiesResponse.json() as Array<{id:string;isActive:boolean;gstin?:string}>;const activeCompanies=companies.filter(c=>c.isActive!==false);const company=activeCompanies[0];if(!company?.id)throw new Error('No active company is configured in the billing database.');const customerTypeValue=customerType==='LEDGER'?'B2B':'B2C';const gstin=newCustomer.gstNumber.trim().toUpperCase();const customerResponse=await fetch('/api/customers',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({companyId:company.id,code:`POS-${Date.now()}`,name:newCustomer.name.trim(),phone:newCustomer.phone.trim(),email:null,gstin:gstin||null,address:newCustomer.address.trim(),billingAddress:newCustomer.address.trim(),shippingAddress:newCustomer.address.trim(),city:newCustomer.city.trim(),state:newCustomer.state.trim(),stateCode:customerTypeValue==='B2B'?newCustomer.stateCode.trim():null,customerType:customerTypeValue,isActive:true})});if(!customerResponse.ok)throw new Error(`Customer creation failed: ${await customerResponse.text()}`);const createdDto=await customerResponse.json() as {id:string;companyId:string;code:string;name:string;phone?:string;email?:string;gstin?:string;address?:string;billingAddress?:string;shippingAddress?:string;city?:string;state?:string;stateCode?:string;customerType:string;isActive:boolean};const created:Customer={id:createdDto.id,companyId:createdDto.companyId,code:createdDto.code,name:createdDto.name,phone:createdDto.phone||newCustomer.phone,email:createdDto.email,gstNumber:createdDto.gstin,address:createdDto.address||newCustomer.address,billingAddress:createdDto.billingAddress||newCustomer.address,shippingAddress:createdDto.shippingAddress||newCustomer.address,city:createdDto.city||newCustomer.city,state:createdDto.state||newCustomer.state,stateCode:createdDto.stateCode||newCustomer.stateCode,customerType:createdDto.customerType==='B2B'?'LEDGER':'NORMAL',isActive:createdDto.isActive,loyaltyPoints:0,totalSpent:0,outstandingBalance:0};const response=await fetch(`/api/billing-categories/customer/${created.id}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({categoryId:billingCategoryId})});if(!response.ok)throw new Error(`Customer created in SQL, but category mapping failed: ${await response.text()}`);setCustomer(created);setCategoryCustomers(cur=>[created,...cur.filter(c=>c.id!==created.id)]);setCreatingCustomer(false);setShowCustomerPanel(false);setNewCustomer(emptyCustomer);setMessage('Customer created in SQL Server and mapped to the selected billing category.')}catch(e){setMessage(e instanceof Error?e.message:'Unable to create and map customer in SQL Server.')}"
if old not in text:
    raise SystemExit("target customer creation block not found")
path.write_text(text.replace(old, new, 1), encoding="utf-8")
