from pathlib import Path

p = Path('src/components/PosBillingView.tsx')
s = p.read_text(encoding='utf-8')

old = """      const res = await lookupGstDetails(targetGst);\n      setGstData(res);\n      if (res.isValid && res.status === 'ACTIVE') {\n        if (!ledgerCustName) {\n          setLedgerCustName(res.tradeName || res.legalName);\n        }\n      }"""
new = """      const res = await lookupGstDetails(targetGst);\n      setGstData(res);\n      if (res.status === 'ACTIVE' && res.isValid) {\n        setLedgerCustName(res.tradeName || res.legalName);\n        setNewCustName(res.tradeName || res.legalName);\n        setNewCustTax(res.gstin);\n        setNewCustBillingAddress(res.address || '');\n        setNewCustCity('');\n        setNewCustState(res.stateName || '');\n        setNewCustStateCode(res.stateCode || '');\n      }"""
if old not in s:
    raise SystemExit('GST handler target not found')
s = s.replace(old, new, 1)

old = """    if (!selectedSalesperson) {\n      setToastNotification('Select a salesperson before saving the bill.');\n      setTimeout(() => setToastNotification(null), 4000);\n      return;\n    }"""
new = """    if (!selectedSalesperson) {\n      setToastNotification('Select a salesperson before saving the bill.');\n      setTimeout(() => setToastNotification(null), 4000);\n      return;\n    }\n\n    if (customerType === 'LEDGER') {\n      const verifiedGstin = gstData?.gstin?.trim().toUpperCase();\n      if (!gstInput.trim() || verifiedGstin !== gstInput.trim().toUpperCase() || gstData?.status !== 'ACTIVE' || !gstData?.isValid) {\n        setToastNotification('B2B/Ledger billing requires successful online GSTIN verification with ACTIVE status.');\n        setTimeout(() => setToastNotification(null), 5000);\n        return;\n      }\n    }"""
if old not in s:
    raise SystemExit('checkout validation target not found')
s = s.replace(old, new, 1)

old = """    if (!finalCustomerObj && customerType === 'LEDGER' && gstInput.trim()) {\n      // Auto-register ledger customer if entered on the fly\n      finalCustomerObj = onAddNewCustomer({\n        name: ledgerCustName || gstData?.tradeName || gstData?.legalName || `Ledger GST (${gstInput})`,\n        phone: ledgerCustPhone || '+91 99000 00000',\n        customerType: 'LEDGER',\n        gstNumber: gstInput.trim(),\n        gstLegalName: gstData?.legalName,\n        gstTradeName: gstData?.tradeName,\n        gstStatus: gstData?.status || 'ACTIVE',\n        gstState: gstData?.stateName,\n        taxNumber: gstInput.trim(),\n        address: gstData?.address || 'Registered Business GST Address'\n      });\n    }"""
new = """    if (!finalCustomerObj && customerType === 'LEDGER' && gstInput.trim() && gstData?.status === 'ACTIVE') {\n      // Only create a B2B customer from verified online GST details.\n      finalCustomerObj = onAddNewCustomer({\n        name: gstData.tradeName || gstData.legalName,\n        phone: ledgerCustPhone || '',\n        customerType: 'LEDGER',\n        gstNumber: gstData.gstin,\n        gstLegalName: gstData.legalName,\n        gstTradeName: gstData.tradeName,\n        gstStatus: 'ACTIVE',\n        gstState: gstData.stateName,\n        taxNumber: gstData.gstin,\n        address: gstData.address,\n        billingAddress: gstData.address,\n        city: '',\n        state: gstData.stateName,\n        stateCode: gstData.stateCode,\n        shippingAddress: gstData.address\n      });\n    }"""
if old not in s:
    raise SystemExit('ledger auto-create target not found')
s = s.replace(old, new, 1)

old = """              {newCustType === 'LEDGER' && (\n                <div>\n                  <label className=\"block text-xs font-medium text-slate-300 mb-1\">GST Number (GSTIN)</label>\n                  <input\n                    type=\"text\"\n                    required\n                    value={newCustTax}\n                    onChange={(e) => setNewCustTax(e.target.value.toUpperCase())}\n                    placeholder=\"24AAAAA1234A1Z5\"\n                    className=\"w-full px-3 py-2 bg-slate-800 border border-slate-700 rounded-xl text-white text-xs font-mono uppercase\"\n                  />\n                </div>\n              )}"""
new = """              {newCustType === 'LEDGER' && (\n                <div className=\"space-y-2 p-3 rounded-2xl bg-emerald-950/20 border border-emerald-500/30\">\n                  <label className=\"block text-xs font-bold text-emerald-300 mb-1\">GSTIN * — verify before entering/saving B2B customer</label>\n                  <div className=\"flex gap-2\">\n                    <input\n                      type=\"text\"\n                      required\n                      value={newCustTax}\n                      onChange={(e) => {\n                        setNewCustTax(e.target.value.toUpperCase());\n                        setGstInput(e.target.value.toUpperCase());\n                        setGstData(null);\n                      }}\n                      placeholder=\"24AAAAA1234A1Z5\"\n                      maxLength={15}\n                      className=\"flex-1 px-3 py-2 bg-slate-800 border border-slate-700 rounded-xl text-white text-xs font-mono uppercase\"\n                    />\n                    <button\n                      type=\"button\"\n                      onClick={() => handleVerifyGst(newCustTax)}\n                      disabled={isVerifyingGst || !newCustTax.trim()}\n                      className=\"px-3 py-2 bg-emerald-600 hover:bg-emerald-500 disabled:opacity-50 text-white text-xs font-bold rounded-xl\"\n                    >\n                      {isVerifyingGst ? 'Checking…' : 'Verify GST'}\n                    </button>\n                  </div>\n                  {gstData && (\n                    <div className={`p-2 rounded-xl border text-[11px] ${gstData.status === 'ACTIVE' ? 'bg-emerald-950 border-emerald-500/50 text-emerald-200' : 'bg-rose-950 border-rose-500/50 text-rose-200'}`}>\n                      <strong>{gstData.status}</strong> — {gstData.message}\n                      {gstData.status === 'ACTIVE' && (\n                        <div className=\"mt-1 space-y-0.5\">\n                          <div>Legal Name: <strong>{gstData.legalName}</strong></div>\n                          <div>Trade Name: <strong>{gstData.tradeName || gstData.legalName}</strong></div>\n                          <div>State: <strong>{gstData.stateName} ({gstData.stateCode})</strong></div>\n                          <div>Registration Date: <strong>{gstData.registrationDate || 'Available from provider'}</strong></div>\n                          <div>Address: <strong>{gstData.address}</strong></div>\n                        </div>\n                      )}\n                    </div>\n                  )}\n                </div>\n              )}"""
if old not in s:
    raise SystemExit('ledger GST field target not found')
s = s.replace(old, new, 1)

# Disable manual editing of business identity/address once GST is verified.
s = s.replace("                  value={newCustName}\n                  onChange={(e) => setNewCustName(e.target.value)}", "                  value={newCustName}\n                  readOnly={newCustType === 'LEDGER' && gstData?.status === 'ACTIVE'}\n                  onChange={(e) => setNewCustName(e.target.value)}", 1)
s = s.replace("                  value={newCustBillingAddress}\n                  onChange={(e) => setNewCustBillingAddress(e.target.value)}", "                  value={newCustBillingAddress}\n                  readOnly={newCustType === 'LEDGER' && gstData?.status === 'ACTIVE'}\n                  onChange={(e) => setNewCustBillingAddress(e.target.value)}", 1)

p.write_text(s, encoding='utf-8')
print('B2B GST verification flow patched.')
